imports:
  - { resource: '../di.yml' }

services:
  collection.factory.set.logger:
    decorates: collection.factory.set
    decoration_priority: 100
    class: Vainyl\Operation\Collection\Decorator\LoggerCollectionFactoryDecorator
    arguments: ['@collection.factory.set.logger.inner', '@logger.operation']
  collection.factory.sequence.logger:
    decorates: collection.factory.sequence
    decoration_priority: 100
    class: Vainyl\Operation\Collection\Decorator\LoggerCollectionFactoryDecorator
    arguments: ['@collection.factory.sequence.logger.inner', '@logger.operation']
  operation.factory.logger:
    decorates: operation.factory
    decoration_priority: 100
    class: Vainyl\Operation\Decorator\LoggerOperationFactoryDecorator
    arguments: ['@operation.factory.logger.inner', '@logger.operation']