services:
  collection.factory.set:
    class: Vainyl\Operation\Collection\Factory\SetCollectionFactory
    arguments: ['@storage.set.prototype']
  collection.factory.sequence:
    class: Vainyl\Operation\Collection\Factory\SequenceCollectionFactory
    arguments: ['@storage.set.prototype']
  logger.operation:
    synthetic: true
    tags:
      - {name: 'logger', channel: 'operation'}
  operation.factory:
    class: Vainyl\Operation\Factory\OperationFactory
